server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false