server:
  port: 8081

spring:
  application:
    name: book-middleware

eureka:
  serviceUrl:
    defaultzone: http://localhost:8761/eureka/

zuul-service-server-url: http://localhost:8762/
app-service-server-url: ${zuul-service-server-url}core/book

logging:
  level:
    root: ERROR